# Generated by Django 5.0.6 on 2024-06-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0001_initial'),
        ('models', '0001_initial'),
        ('qsar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.model')),
                ('molsets', models.ManyToManyField(related_name='maps', to='compounds.molset')),
            ],
            options={
                'abstract': False,
            },
            bases=('models.model',),
        ),
        migrations.CreateModel(
            name='MappingStrategy',
            fields=[
                ('trainingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.trainingstrategy')),
                ('descriptors', models.ManyToManyField(to='qsar.descriptorgroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.trainingstrategy',),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='maps.map')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.molecule')),
            ],
        ),
    ]
