# Generated by Django 5.0.6 on 2024-06-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDFCompounds',
            fields=[
                ('molset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.molset')),
                ('activitiesProp', models.CharField(default='GENUI_ACTIVITIES', max_length=256)),
                ('activityTypesProp', models.CharField(default='GENUI_ACTIVITY_TYPES', max_length=256)),
                ('activityUnitsProp', models.CharField(blank=True, default='GENUI_ACTIVITY_UNITS', max_length=256, null=True)),
                ('dataSeparator', models.CharField(default=',', max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.molset',),
        ),
        migrations.CreateModel(
            name='SDFMolecule',
            fields=[
                ('molecule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.molecule')),
                ('name', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.molecule',),
        ),
    ]
