# Generated by Django 5.0.6 on 2024-06-11 12:12

import django.db.models.deletion
import genui.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source',
            field=models.ForeignKey(on_delete=genui.utils.models.NON_POLYMORPHIC_CASCADE, related_name='activities', to='compounds.activityset'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.activitytypes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.activityunits'),
        ),
        migrations.AlterUniqueTogether(
            name='chemicalentity',
            unique_together={('canonicalSMILES', 'inchiKey')},
        ),
        migrations.AddField(
            model_name='molecule',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecules', to='compounds.chemicalentity'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='compounds.molecule'),
        ),
        migrations.AddField(
            model_name='moleculepic',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='compounds.molecule'),
        ),
        migrations.AddField(
            model_name='molset',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='molset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='molecule',
            name='providers',
            field=models.ManyToManyField(related_name='molecules', to='compounds.molset'),
        ),
        migrations.AddField(
            model_name='activityset',
            name='molecules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='compounds.molset'),
        ),
        migrations.AddField(
            model_name='molsetexport',
            name='molset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='compounds.molset'),
        ),
        migrations.AddField(
            model_name='molsetexport',
            name='exporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.molsetexporter'),
        ),
        migrations.AddField(
            model_name='molsetfile',
            name='export',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='compounds.molsetexport'),
        ),
        migrations.AddField(
            model_name='molsetfile',
            name='molset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='compounds.molset'),
        ),
        migrations.AddField(
            model_name='molsetfile',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='moleculepic',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.pictureformat'),
        ),
    ]
