# Generated by Django 5.0.6 on 2024-06-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0001_initial'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('corePackage', models.CharField(default='genui.qsar.genuimodels', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.activity')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('compounds.activity',),
        ),
        migrations.CreateModel(
            name='QSARModel',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.model')),
                ('molset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='compounds.molset')),
                ('predictionsType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.activitytypes')),
                ('predictionsUnits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.activityunits')),
            ],
            options={
                'abstract': False,
            },
            bases=('models.model',),
        ),
        migrations.CreateModel(
            name='ModelActivitySet',
            fields=[
                ('activityset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compounds.activityset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='qsar.qsarmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('compounds.activityset',),
        ),
        migrations.CreateModel(
            name='QSARTrainingStrategy',
            fields=[
                ('trainingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.trainingstrategy')),
                ('activityThreshold', models.FloatField(null=True)),
                ('activitySet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.activityset')),
                ('activityType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.activitytypes')),
                ('descriptors', models.ManyToManyField(to='qsar.descriptorgroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.trainingstrategy',),
        ),
    ]
